name: Genera PDF

on:
  push:
    branches: [ main ]
    paths:
      - 'intro/*.*'
      - 'intro/assets/*.*'
      - 'intro2/*.*'
      - 'intro2/assets/*.*'
      - '.github/workflows/*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: generate pdf
      run: | 
        cd intro
        docker run --rm --init -v $PWD:/home/marp/app/ -e LANG="it_IT.UTF-8" -e MARP_USER="$(id -u):$(id -g)" marpteam/marp-cli intro.md --pdf --allow-local-files
        cd ../intro2
        docker run --rm --init -v $PWD:/home/marp/app/ -e LANG="it_IT.UTF-8" -e MARP_USER="$(id -u):$(id -g)" marpteam/marp-cli intro2.md --pdf --allow-local-files
      
    - name: commit & push
      run: |
        git add -A
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update slide files"
        git push
        
